In [ ]:
def dictionaryKeyFile(keyfile):
    key = {}
    with open('DataFiles/key.txt','r') as f:
        for line in f:
            line = line.split()
            key[line[0]] = line[1]
    return key
keyfile = "DataFile/key.txt"
key = dictionaryKeyFile(keyfile)
evenkey = {item for item in key}
evenkey

# Libraries for Data Science

* Processing N-Dimensional arrays

In [42]:
import numpy as np

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
x1
print(x2)
x3

[[2 8 4 6]
 [8 2 8 5]
 [7 7 9 5]]


array([[[8, 0, 9, 2, 0],
        [9, 6, 7, 6, 7],
        [1, 7, 0, 5, 4],
        [3, 4, 7, 7, 0]],

       [[5, 5, 1, 1, 4],
        [1, 9, 9, 0, 4],
        [0, 4, 6, 1, 7],
        [4, 8, 2, 7, 6]],

       [[8, 1, 2, 7, 4],
        [6, 9, 6, 8, 4],
        [3, 9, 1, 0, 2],
        [9, 2, 4, 7, 2]]])

In [43]:
print("x3 ndim: ", x3.ndim) # num of dimensioms   --4
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [44]:
print("dtype:", x3.dtype)

dtype: int32


In [58]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [63]:
list("hjdsg").count('d')

1

# Pandas

* Series 
* DataFrames


In [68]:
import pandas as pd

internall = {"s1":21,"s2":18,'s3':24}
    
internall = pd.Series(internall)

internal2 = {'s1':15, 's2':18,'s3':12}

internal2 = pd.Series(internal2)

internal2

s1    15
s2    18
s3    12
dtype: int64

In [74]:
final = {'Internal1':internall, 'Internal2': internal2}
final= pd.DataFrame(final)
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [75]:
final.values

array([[21, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [76]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [83]:
final.drop('s1')

Internal1  Internal2
s2         18         18
s3         24         12

In [84]:
for row in final.values:
    print('internal1-',row[0],'internal2',row[1])

internal1- 21 internal2 15
internal1- 18 internal2 18
internal1- 24 internal2 12


In [85]:
final.values[2,0] =77

# Reading CSV file data


In [92]:
import pandas as pd

filepath = 'DataFiles/Income.csv'
incomedataframe =  pd.read_csv(filepath)
incomedataframe

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [94]:
# avg Income of arizona

s = 0
for i in range(2,11):
    s +=incomedataframe.values[2][i]
s/len(incomedataframe.values[2][2:])

47214.77777777778

In [103]:
for r in incomedataframe.values:
    print(r[1],' : ',r[-1])

Alabama  :  41381
Alaska  :  61137
Arizona  :  50602
Arkansas  :  39919
California  :  57528


In [106]:
# avg income of all states 
sum = 0
for row in incomedataframe.values:
    #sum += row[-9][-1]
    print(row[2]:[-1])

SyntaxError: invalid syntax (<ipython-input-106-e4a06fa8e7b5>, line 5)